### ISSUE TITLE
Issue running as a script invoked by Automate Control

### ISSUE THREAD

**Issue by jhlusk2** [itglue/powershellwrapper#101]
Might not be a bug, but looking for some help.  I have the following code and it works when I run it from the console;

$data = @{
    'type' = 'passwords'
    'attributes' = @{
        'name' = 'Test Creation'
        'username' =  "test"
        'password' = "password123"
        'password_category_id' = xxxxxx
        'notes' = "Admin credentials for the xxxx admin account"
        'organization_id' = xxxxxxx
    }
}

I then use Automate Control to invoke this script and when it does I get the following message and error;

ITGlueAPI Module configuration loaded successfully from C:\Windows\system32\config\systemprofile\ITGlueAPI\config.psd1!
New-ITGluePasswords : Exception calling ".ctor" with "2" argument(s): "Cannot 
process argument because the value of argument "password" is null. Change the 
value of argument "password" to a non-null value."
At C:\xxxxxx\createpass.ps1:12 char:1
+ New-ITGluePasswords -data $data
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorExcep 
   tion
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorExceptio 
   n,New-ITGluePasswords

 I have tried converting the password "$password = "xxxxxx" | ConvertTo-SecureString -AsPlainText -Force" but the wrapper doesn't seem to understand that

Is there something I am missing here or should be doing differently?

**Comment by christiannancy** [comment]
Could it be that the config.psd1 file contains a Windows SecureString that was encoded with your own Windows user and is now read by LOCAL\SYSTEM and cannot be decoded properly (only the creator of a SecureString can decode it)?

For this to work as you report it, the configuration would have to be done while logged in as LOCAL\SYSTEM as well (you’d redo your ITG module configuration while in a PSExec session as SYSTEM).

I’m not sure if that would actually work but this seem like a possible reason for it not working in that scenario.

My 2 cents,
Christian

**Comment by jhlusk2** [comment]
That might be exactly what it is. Since Automate uses the local system to execute. I copied it from my user. I thought it was unique to the machine, not the user. I will redo the module config under the system session and then try it again.  Thanks

**Comment by jhlusk2** [comment]
That was it. Glad it was so simple and sorry it was so simple.
