### ISSUE TITLE
Unprocessable Entity","detail":"Request contains invalid trait keys"

### ISSUE THREAD

**Issue by snowburn** [itglue/powershellwrapper#102]
Error:
New-ITGlueFlexibleAssets : {"errors":[{"status":422,"title":"Unprocessable Entity","detail":"Request contains invalid trait keys","source":{"pointer":"data/attributes/traits"}}]}

Steps:

I've been trying to upload sonicwall interface data to ITGlue as an "AutoDoc" and get this invalid trait key error. I've double checked everything and even just got out of the for loop i created and tried to just update, one field. Sample data is below:

    $FlexAssetBody = 
    @{
        Type = "flexible-assets"
        Attributes = @{
                name = $FlexAssetName
                traits = @{
                    "int-name" = $name
                }
        }

$NewFlexAssetData = 
        @{
            Type = 'flexible-asset-types'
            Attributes = @{
                    name = $FlexAssetName
                    icon = 'sitemap'
                    description = $description
            }
            relationships = @{
                "flexible-asset-fields" = @{
                    data = @(
                        @{
                            Type       = "flexible_asset_fields"
                            Attributes = @{
                                order           = 1
                                name            = "Name"
                                kind            = "Textbox"
                                required        = $true
                                "show-in-list"  = $true
                            }
                        }
                    )
                    }
                }
            }

New-ITGlueFlexibleAssets -data $FlexAssetBody

I am very new to this API. If someone can help me figure out why I'm getting this error, it will be much appreciated.

**Comment by ecspresso** [comment]
Are you trying to create a new flexible asset type or a new flexible asset?

This here looks like you are trying to create a new flexible asset but you are missing some information.
Look at the documentation: https://api.itglue.com/developer#flexible-assets-create
```
$FlexAssetBody =
@{
    Type = "flexible-assets"
    Attributes = @{
            "organization-id" = $orgId # missing
            "flexible-asset-type-id" = $flexAssetTypeId # missing
            name = $FlexAssetName
            traits = @{
                "int-name" = $name
            }
    }
} # One bracket was also missing
```

**Comment by snowburn** [comment]
Thank you ecspresso! I figured it out! It didn't like traits that didn't match variables (I think).
