### ISSUE TITLE
Issue running the module commandlets twice using Azure Function

### ISSUE THREAD

**Issue by EricB-OnestepIT** [itglue/powershellwrapper#107]
Hello!

I've made a small script that is supposed to run as an Azure Function. Everything works the first time a request is received but on the second request I get this error message regarding Convert-Json Depth:

ERROR:` Cannot validate argument on parameter 'Depth'. The argument is null, empty, or an element of the argument collection contains a null value. Supply a collection that does not contain any null values and then try the command again.

Exception             : 
    Type              : System.Management.Automation.ParameterBindingValidationException
    Message           : Cannot validate argument on parameter 'Depth'. The argument is null, empty, or an element of the argument collection contains a null value. Supply a collection that does not contain any null values and then try the command again.
    ParameterName     : Depth
    ParameterType     : int
    ErrorId           : ParameterArgumentValidationError
    Line              : 247
    Offset            : 54
    CommandInvocation : 
        MyCommand        : ConvertTo-Json
        BoundParameters  : 
            Comparer : System.OrdinalIgnoreCaseComparer

**Steps to reproduce**

Run attached script in an Azure Function, both localy or in Azure

**Expected behavior**

Expected behaviour is that the script should run the same way every time.

**Actual behavior**

A very long error message.

**Environment**

Please share additional details about your environment. Version information for:
* PowerShell 7.0.3
* ITGlueAPI 2.0.9
* Operating System Windows 10 Pro 2004
OsName               : Microsoft Windows 10 Pro
OsOperatingSystemSKU : 48
OsArchitecture       : 64 bitar
WindowsVersion       : 2004
WindowsBuildLabEx    : 19041.1.amd64fre.vb_release.191206-1406
OsLanguage           : sv-SE
OsMuiLanguages       : {sv-SE}

**Comment by EricB-OnestepIT** [comment]
[run.txt](https://github.com/itglue/powershellwrapper/files/5163822/run.txt)

**Comment by EricB-OnestepIT** [comment]
I actually solved it my self by entering this line before any ITG commandlets were used.

$global:ITGlue_JSON_Conversion_Depth = 100

**Comment by christiannancy** [comment]
Great!

Let me review all that information this afternoon and get back to you if I have questions.

Thank you,


Christian Nancy
Chief Technical Officer
Wooden Spoon Technologies, LLC
(707)523-2222 x140
