### ISSUE TITLE
Documentation Support

### ISSUE THREAD

**Issue by RCarlevaleSS** [itglue/powershellwrapper#111]
Chances are this is on ITGlue's end, but is there any chance that there can be support added for uploading documents? Seems kind of counter intuitive to not include a way to upload documents as a documentation-focused company.

**Comment by CalebAlbers** [comment]
Unfortunately, there is no API for managing documents other than being able to edit settings like document name, permissions, etc:

```json
{
  "data": {
    "type": "documents",
    "attributes": {
      "name": "Document Name",
      "archived": true,
      "restricted": false,
      "public": false,
    }
  }
}
```

I'll be adding that support in a PR later today, but I'd suggest reaching out to IT Glue and giving them feedback about needing the ability to actually modify documents.

**Comment by CalebAlbers** [comment]
PR #114 added support for the document metadata updates
