### ISSUE TITLE
There is no documents, how can we use documents?

### ISSUE THREAD

**Issue by biyro02** [itglue/powershellwrapper#116]
Hi,
When I'm researching about your API documentation, I realized that: there is no GET request for documents endpoint. I want to get documents inside to our application like your documents UI. I wonder that, is it possible with your API? Or how can I reach all documents by your API?
If there is not, you should do GET request for this endpoint.
Thanks a lot.

**Comment by CalebAlbers** [comment]
Hey @biyro02,

I don't work for IT Glue, but I'd like to mention that currently, IT Glue does not have a public API for managing Documents. There have been other Issues asking for similar things (#111, for example). The best way to push for that support is by providing feedback in IT Glue's feature portal and reaching out to your rep.

Cheers!
