### ISSUE TITLE
Managing folders

### ISSUE THREAD

**Issue by trixrahbit** [itglue/powershellwrapper#120]
Is there a way to manage the folders withing the passwords and documents section? Id like to automate my folder creation. It bores me.

**Comment by CalebAlbers** [comment]
Hey @trixrahbit!

IT Glue's API doesn't currently support managing password or document folders. I encourage you to reach out to your account manager with it as a feature request, though.

**Comment by trixrahbit** [comment]
Makes sense! Maybe they will add it when they release multiple columns :-D :-D :-D Thanks for the info and scripts!
