### ISSUE TITLE
New Get Logs API Capability Enhancement

### ISSUE THREAD

**Issue by jausburn-edafio** [itglue/powershellwrapper#137]
**Is your feature request related to a problem? Please describe.**
IT Glue has made their activity logs available via the API and I'm not nearly enough of a programmer to understand how to design a new function for a PowerShell Module :(

**Describe the solution you'd like**
I'd like to add a cmdlet called "Get-ITGlueLogs" with switches for sorting based on created_at or updated_at with options for ascending or descending, which outputs the results into a standard json output like the other cmdlets in this module.

**Describe alternatives you've considered**
I can't really think of any alternatives since this _seems_ to be straightforward.

**Additional context**
https://api.itglue.com/developer/#logs-index

**Comment by CalebAlbers** [comment]
Closed via #139 (thanks, Celerium!). This will ship with `v2.2.0` within the next week.
