### ISSUE TITLE
Get-ITGlueContacts doesn't have an organization_id parameter

### ISSUE THREAD

**Issue by ronfowler** [itglue/powershellwrapper#14]
I don't see an organization_id parameter on the Get-ITGlueContacts function in the Contacts.ps1 file however the standard if - check for $organization_id is present in the Get-ITGlueContacts function.

I've added to my copy and it seems to address my issue:
        [Parameter(ParameterSetName="index")]
        [Parameter(ParameterSetName="show")]
        [Nullable[Int]]$organization_id = $null

**Comment by ecspresso** [comment]
A workaround until then is `(Get-ITGlueContacts -page_size (Get-ITGlueContacts).meta.'total-count').data | where {$_.attributes.'organization-id' -eq $organization_id}` for those who are not adding the above to their module or are sharing their code with others.

**Comment by CalebAlbers** [comment]
This is now fixed as of the v2.0.0 release that is pending in #28. It will be merged into Master this week.
