### ISSUE TITLE
All commands get "Specified value has invalid Control characters." error

### ISSUE THREAD

**Issue by mrobinson-ws** [itglue/powershellwrapper#141]
**Steps to reproduce**

Installed Module, added API key, exported settings, ran Get-ITGlueOrganizations, received error.  Tried Get-ITGlueConfigurations, same error.  All functions have same error.

**Expected behavior**

Pull data as I am trying to update multiple organizations and am in the learning/testing phase.

**Actual behavior**

Error as listed.

**Screenshots**

![image](https://user-images.githubusercontent.com/84938976/174399048-4d20fdaa-135a-418a-a49b-91ecd94b03eb.png)

**Environment**

Please share additional details about your environment. Version information for:
* PowerShell - 5.1.19041.1682
* ITGlueAPI - 2.1.0
* Operating System - 
OsName               : Microsoft Windows 10 Pro
OsOperatingSystemSKU : 48
OsArchitecture       : 64-bit
WindowsVersion       : 2009
WindowsBuildLabEx    : 19041.1.amd64fre.vb_release.191206-1406
OsLanguage           : en-US
OsMuiLanguages       : {en-US}

**Comment by Absoblogginlutely** [comment]
Not sure if this screenshot is edited, but you will need to add-itgluebaseuri to point to your instance.
Also, the api key you need to enter is more than one character that is shown on your screenshot
Reproducing the issue per your screenshot gives a different error for me which states access forbidden (as expected)

**Comment by mrobinson-ws** [comment]
1)  The BaseURI is default, https://api.itglue.com which it automatically added when I added the API key, with no change I saw no reason to run the command.

2)  I am unsure why it only shows one character, it's pasted in, but I did notice on my personal PC that it shows all the characters as asterisks instead, and I get no errors.  I will attempt again soon.  Thanks.

**Comment by Absoblogginlutely** [comment]
1. Good point :-)
2.  I've had this happen before when copying a password from ITGlue (ironically enough) fails to actually copy so the clipboard doesn't have accurate content when I paste into the website. Although typically it (seems to be)  blank rather than one character.

**Comment by mrobinson-ws** [comment]
That did it, thanks!
