### ISSUE TITLE
Remove version bump instruction from CONTRIBUTING.md

### ISSUE THREAD

**Issue by davidhaymond** [itglue/powershellwrapper#148]
If each PR bumps the version number independently, it will lead to merge conflicts. The version number should only be bumped by the maintainer when publishing a new release.

**Comment by adrianwells** [comment]
@davidhaymond seems reasonable. Wonder how it ties into #147 if at all?

**Comment by davidhaymond** [comment]
@adrianwells There's a few ways you could set it up, but my recommendation would be to configure GitHub Actions to publish to the PS Gallery when a new release is created in GitHub. The process would be the following:

1. Merge any PRs and development branches you wish to include in the release. (This should probably be done regularly anyways.)
2. Bump the version number in `master` according [semantic versioning](https://semver.org/) guidelines.
3. Create an annotated tag and a release and add release notes. GitHub Actions automatically publishes the current state of the `master` branch to PS Gallery.

Of course, if you're planning on a minor release, you wouldn't want to merge any breaking changes until you're ready for a major release.

**Comment by CalebAlbers** [comment]
+1 for semver on release and moving that out of the contribution guide. There are some nice tools like `semantic-commit` which can auto-infer semver, but given the most common external contributor for this repo is a fly-by IT person with a specific need, having them conform to specific commit syntax sounds like a potentially heavy requirement.

Also, given the release frequency, creating the release and having a GHA workflow triggered on `release` events is a pretty easy thing to do.
