### ISSUE TITLE
Move all calls to the API to a new internal function

### ISSUE THREAD

**Issue by ecspresso** [itglue/powershellwrapper#151]
**Is your feature request related to a problem? Please describe.**
Create a new internal function that handles all the actual calls to the API.

**Describe the solution you'd like**
```posh
function New-ITGlue {
    param(
        $URI,
        $Data
    )
    $body = ConvertTo-Json -InputObject $body -Depth $ITGlue_JSON_Conversion_Depth

    try {
        $ITGlue_Headers.Add('x-api-key', (New-Object -TypeName System.Management.Automation.PSCredential -ArgumentList 'N/A', $ITGlue_API_Key).GetNetworkCredential().Password)
        $rest_output = Invoke-RestMethod -method 'POST' -uri $URI -headers $ITGlue_Headers `
            -body $body -ErrorAction Stop -ErrorVariable $web_error
    } catch {
        Write-Error $_
    } finally {
        [void] ($ITGlue_Headers.Remove('x-api-key')) # Quietly clean up scope so the API key doesn't persist
    }

    $body = @{}

    $body += @{'data'= $data}

    $data = @{}
    $data = $rest_output
    return $data
}
```
```posh
function New-ITGlueContacts {
    Param (
        [Nullable[Int64]]$organization_id = $null,

        [Parameter(Mandatory = $true)]
        $data
    )

    $resource_uri = '/contacts'

    if ($organization_id) {
        $resource_uri = ('/organizations/{0}/relationships/contacts' -f $organization_id)
    }

    return New-ITGlue -URI ($ITGlue_Base_URI + $resource_uri) -Data $data
    
}
```

**Additional context**
Doing this would mean easier maintenance. Any change to how the API is called (for example, UTF-8 support, removing body from the GET requests) would only have to be changed in one place instead of 40+.

Each function would pass its URL and all other parameters needed to the internal function, this function would handle the call and response and pass it back to the original caller.

**Comment by ecspresso** [comment]
Issues like #66 would be quite the undertaking to fix and mistakes easy to miss because of all the places where the change needs to be implemented. This would simplify that a lot.

**Comment by ecspresso** [comment]
I could draft PR if you all approve.

**Comment by ecspresso** [comment]
Moved $body to the internal method because that makes more sense.

**Comment by davidhaymond** [comment]
I think this is a great suggestion and will reduce code duplication and ease maintenance. I was also planning to start work on a more general refactoring but might not get to it right away, so feel free to draft a PR.
