### ISSUE TITLE
Import-Module : The given assembly name or codebase was invalid. (Exception from HRESULT: 0x80131047)

### ISSUE THREAD

**Issue by adrianwells** [itglue/powershellwrapper#20]
@CalebAlbers creating this issue to separate the comment I made in #9 
I resolved this issue by adding a missing file and made a PR https://github.com/CalebAlbers/powershellwrapper/pull/1 to resolve this

**Comment by CalebAlbers** [comment]
Awesome; Thanks, Adrian!
