### ISSUE TITLE
Get-ITGlueConfigurations does not utilize -include

### ISSUE THREAD

**Issue by mrmarkwest** [itglue/powershellwrapper#23]
Body variable should look like this (tested and confirmed works)
        $body = @{
            'filter[name]'          = $filter_name
            'filter[serial-number]' = $filter_serial_number
            'sort'                  = $sort
            'include'               = $include
        }

**Comment by CalebAlbers** [comment]
Thanks, @mrmarkwest! This functionality is in the development branch and will be pushed to production after I finish code review and testing this weekend.

I'm keeping this open until then as a reminder.

**Comment by CalebAlbers** [comment]
Hey @mrmarkwest, I wanted to give a heads up and say that `-include` is now in place for all supported endpoints as of the #28 release pull request. This will be merged into the master branch this week.

Thanks!

**Comment by bjowol** [comment]
Add this validateset to the $include parameter block:
[ValidateSet('adapters_resources', 'configuration_interfaces', 'rmm_records', 'passwords', 'attachments', 'tickets', 'user_resource_accesses', 'group_resource_accesses')]

Applies to pretty much all the functions
