### ISSUE TITLE
Configuration & Configuration Interfaces uses int32 instead of int64

### ISSUE THREAD

**Issue by LeslieVBH** [itglue/powershellwrapper#24]
This used to be fine, but recently I've noticed the number is larger then allowed for int32.
On my end I've changed both files to use int64 and it resolved this issue.

**Comment by adrianwells** [comment]
@LeslieVBH - this appears to have been resolved by @MortenRei's [commit](https://github.com/itglue/powershellwrapper/commit/fb022cefa694fed99f5559e85dc77b2a599d01f2).  Can @CalebAlbers or another contributor please review and mark this as resolved if appropriate?  Thank you.

**Comment by CalebAlbers** [comment]
@adrianwells is correct. The current code in the master branch uses `Int64`. @LeslieVBH please re-open if you find any issues with the new(er) code.
