### ISSUE TITLE
Exception calling "Add" with "2" argument(s): "An item with the same key has already been added."

### ISSUE THREAD

**Issue by ecspresso** [itglue/powershellwrapper#29]
If wrapping the ITGlue call in a try-catch and it fails, it will enter the catch and exit before it can remove the API key. Invoke-RestMethod returns error and catch catches the error and exits.

```posh
$configuration = @{
    key = "value"
}

try {
    New-ITGlueConfigurations -data $configuration
} catch {
    Write-Error $_
}

Exception calling "Add" with "2" argument(s): "An item with the same key has already been added."
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Untitled1.ps1
```
<br>
<br>

One way to solve the problem is the check the header for 'x-api-key' and remove if it is there:
```posh
if($ITGlue_Headers.'x-api-key') {
    $ITGlue_Headers.Remove('x-api-key') >$null
}
```

<br>
Another options is to warp it in a try catch, this would let you handle return of data etc and not exit to "external" try-catch:

```posh
try {
    $ITGlue_Headers.Add('x-api-key', (New-Object -TypeName System.Management.Automation.PSCredential -ArgumentList 'N/A', $ITGlue_API_Key).GetNetworkCredential().Password)
    $rest_output = Invoke-RestMethod -method 'POST' -uri ($ITGlue_Base_URI + $resource_uri) -headers $ITGlue_Headers `
        -body $body -ErrorAction Stop -ErrorVariable $web_error
} catch {
    Write-Error $_
} finally {
    # Possible to handle returns here
    # $data = @{}
    # $data = $rest_output 
    # return $data
    $ITGlue_Headers.Remove('x-api-key') >$null # Quietly clean up scope so the API key doesn't persist
}
```

**Comment by CalebAlbers** [comment]
Thanks for pointing this out, Emile! I hadn't incorporated try-catch
statements during testing of the individual functions.

I like the try-catch-finally suggestion. That also paves the way for better
error handling based on what IT Glue's API returns. Currently, errors
returned from the API and then packaged by the `Invoke-RestMethod` cmdlet
are not very user friendly. Some additional processing could easily sit in
the `catch` statement prior to returning the error.

I'll implement this later today and push the changes to the PR #28 branch.

Thanks!
