### ISSUE TITLE
Unable to bulk update on flexible assets

### ISSUE THREAD

**Issue by gavsto** [itglue/powershellwrapper#31]
I am not sure whether this is something that has been implemented as part of this, but it's not possible to implement a bulk update within the Set-ITGlueFlexibleAsset cmdlets.

I believe this is because on line 112 of https://github.com/itglue/powershellwrapper/blob/master/ITGlueAPI/Resources/FlexibleAssets.ps1 the parameter set name cannot be resolved when just a $data parameter is sent (the ID parameter does not exist/is not used in a bulk update. This leads to a situation where Powershell will throw:

`Set-ITGlueFlexibleAssets : Parameter set cannot be resolved using the specified named parameters.` 

Because it cannot determine what parameter set to use.

If there's a way round this I'd love to hear it or maybe I am calling this wrong.

**Comment by ecspresso** [comment]
`DefaultParameterSetName` is set to `index` but there is no `ParameterSetName` with the name index, wouldn't this be the problem?

**Comment by ecspresso** [comment]
Purposed a change in [here](https://github.com/itglue/powershellwrapper/compare/master...ecspresso:patch-1).
