### ISSUE TITLE
unable to create embedded passwords

### ISSUE THREAD

**Issue by jakaaaal** [itglue/powershellwrapper#38]
When trying to create an embedded password they always defaults to a general one, even though I specify resource type and id.

heres my code:

```
$body = @{
	type = 'passwords'
	attributes = @{	   
		organization_id = 115684975
		name = 'test password'
		username = 'root'
		password = 'RByx24fBkDiW'
		resource_type_id = 'configurations'
		resource_id = 1123548497
	} 
}
New-ITGluePasswords -data $body
```

**Comment by adrianwells** [comment]
@jakaaaal - Hello.  I am seeing similar behavior as well so far in my testing.  Will look at it further.

**Comment by adrianwells** [comment]
@jakaaaal thought part of the issue is the use of `resource_type_id` vs. `resource_type` per the [API docs](https://api.itglue.com/developer/)

**Comment by jakaaaal** [comment]
Hello!

The problem appears to not be related to the powershell wrapper itself since this code has the same issue

```
$ITGlue_Headers = @{
    'x-api-key' = 'ITG.cE3R...'
    'Content-Type' = 'application/vnd.api+json; charset=utf-8'
}
$body = @{
	data = @{
		type = 'passwords'
		attributes = @{	   
			organization_id = 115684975
			resource_type = 'configurations'
			resource_id = 1123548497
			name = 'test password'
			username = 'root'
			password = 'RByx24fBkDiW'
		}
	} 
}
$body = ConvertTo-Json -InputObject $body -Depth 10
Invoke-RestMethod -method 'POST' -uri ("https://api.eu.itglue.com/passwords/") -headers $ITGlue_Headers -body $body
 
```

**Comment by adrianwells** [comment]
@jakaaaal - if you have not already, recommend contacting IT Glue support.

**Comment by jakaaaal** [comment]
I have been in contact with IT Glue support they said that they were aware of the bug and are currently working on a fix.

**Comment by adrianwells** [comment]
@jakaaaal, thank you for the update.  Will await hearing more.

**Comment by adrianwells** [comment]
@CalebAlbers  is it possible to tag this issue indicating it's awaiting Itglue API updates?

**Comment by ecspresso** [comment]
ITGlue claims to have fixed this, I get `Invoke-RestMethod : {"errors":[{"status":"unprocessable_entity","title":"configurations is not a valid resource type","source":{"pointer":null}}]}`

Anyone else had the time to try this out?
