### ISSUE TITLE
Integer sizes - ID fields and page numbers need to support int64 values

### ISSUE THREAD

**Issue by MortenRei** [itglue/powershellwrapper#4]
A lot of the INT values are just INT32 and should have been INT64 to support larger number than 2147483647. As an example, my asset ID's are way beyond 460000000000000 today.

**Comment by MortenRei** [comment]
IS there any chance on getting permissions on the repo to create a new branch and commit the fixes I've done?

Per now, I've done the following to all files;

Improvements;
- Changed relevant int values to int64 to handle larger IDs
- Updated commands with missing positional arguments
- Removed all double-quoted strings and replaced them with the -f operator and single quoted strings

Other:
- Replaced write-host with write-verbose. Write-should never be used, as it clutters the outstream
- Formatted all files to improve readability.

**Comment by CalebAlbers** [comment]
Hey MortenRei,

Thanks for the feedback! You made good points all around.

If you would be willing to share your changes, please fork the repo and make a merge request with the updated code. None of the changes you mentioned should break anything, but I try to make it a habit of testing each request before merging into Master.

Thanks again!
