### ISSUE TITLE
Forbidden

### ISSUE THREAD

**Issue by ckortenhorst** [itglue/powershellwrapper#48]
The module has added fine but I am getting on the wrapper forbidden. Tried a few commands and parameters but not working. What am I doing wrong? 

<img width="557" alt="screen shot 2018-10-26 at 23 18 08" src="https://user-images.githubusercontent.com/5760635/47594923-76a92e00-d975-11e8-86ff-61b44ff02e24.png">

**Comment by ecspresso** [comment]
I have seen this a few times. Make sure you are sending requests to the correct data center (EU/US) and that your API key correct. And do not forget to save your settings after you have set them with `Export-ITGlueModuleSettings`.

**Comment by ckortenhorst** [comment]
Yup that was the issue. Thanks
