### ISSUE TITLE
Wrapper not handling integers larger than 32 bits

### ISSUE THREAD

**Issue by luisgiraldo** [itglue/powershellwrapper#49]
PowerShell and .NET seem to default to a 32-bit integer length for numbers, and when given a number larger than the value range permitted by the [int] or [int32] data type in PowerShell, it errors out not able to handle the conversion.

In the EU IT Glue datacenter, some FA Type IDs are large numbers, e.g. 252184228577457, which cannot be converted successfully with a default data type of [int] or [int32].

It's possible to handle larger numbers by using the [long] data type, which can successfully convert a larger-than-32-bit number. Is it possible for the wrapper to account for numbers of any size, or could it default to a [long] data type somehow to avoid this issue?

PowerShell data type reference:
https://ss64.com/ps/syntax-datatypes.html

![image](https://user-images.githubusercontent.com/2345656/47777057-21408a00-dcb1-11e8-9353-311cb87a7fda.png)

**Comment by ecspresso** [comment]
Did they not change from [int] to [int64] to address this issue already?

**Comment by CalebAlbers** [comment]
@luisgiraldo have you or a partner run into this problem specifically? As @ecspresso mentioned, we implemented support for all `ID` values to `[int64]` in https://github.com/itglue/powershellwrapper/commit/fb022cefa694fed99f5559e85dc77b2a599d01f2, which should accommodate large IDs.

I don't have an IT Glue account that has any large IDs, but I'd be willing to test if you had an account in the EU datacenter (or could migrate the current sandbox account to EU) that I could use for troubleshooting.

**Comment by adrianwells** [comment]
@luisgiraldo, Hello. Is this an issue that can be reproduced for further review?  Or is it covered with the past changes as @ecspresso and @CalebAlbers noted?

**Comment by CalebAlbers** [comment]
I've tested this with an IT Glue tenant in the EU datacenter and haven't been able to reproduce it, yet. I'm fairly certain everything should be correct now, as the wrapper uses `int64` throughout.

Problems might arise when someone is crafting an object that they are sending to the API (i.e. a bulk update request, where they have to pass the org IDs inside the actual `data` object), like so:
```Powershell
"data": [
  {
    "type": "organizations",
    "attributes": {
      "id": 252184228577457,
      "organization-status-id": 70
    }
  }
  }
]
```

In that situation, prefix it with `[int64]`. The PowerShell wrapper is not currently built to validate user data, but instead passes it along to IT Glue, validating only the actual function variables.

With that said, I'm going to close. We can re-open if someone encounters the error again.
