### ISSUE TITLE
Get-ITGlueConfigurations improperly chooses nested relationships route

### ISSUE THREAD

**Issue by christiannancy** [itglue/powershellwrapper#52]
How to reproduce:

`Get-ITGlueConfigurations -id 12345`

Returns error 404 - Not found

`Get-ITGlueConfigurations -id 12345 -origanization-id 6789`

Returns the correct Configuration

I believe this is due to a misinterpretation of the API definition for GetConfigurations SHOW. The API states that organization_id is required, but the Validation section states it is only required if using nested relationships route.

Based on that the current code forces resource_uri to be set for nested relationships route, even if the organization_id is not specified.

Commenting out lines 141 through 144 (removing the else section) fixes the issue and allow Configurations to be pulled by their ID alone (as the API documentation implies).

Thank you

**Comment by adrianwells** [comment]
@christiannancy - Hello.  I may not be understanding this reported issue but when testing this ITGlueAPI module v2.0.5 it returns a valid Configuration, sample code where a Configuration ID is passed along
`Get-ITGlueConfigurations -id 10840504`
or the following to see the returned data in more human readable format
`(Get-ITGlueConfigurations -id 10840504).data | Format-List`

May you please provided which version of the ITGlueAPI module you are working with?

**Comment by christiannancy** [comment]
Hi Adrian, I was using the older version of the wrapper, before you pushed 2.0.5. If it works for you on 2.0.5 then we're good, I'll download the latest version. I think you can close this bug as resolved. Thanks for checking!

**Comment by adrianwells** [comment]
@christiannancy, OK. Thanks for the quick reply. Will close for now.
