### ISSUE TITLE
Update AD user password in IT GLue

### ISSUE THREAD

**Issue by ggill27** [itglue/powershellwrapper#54]
HI,

Not sure , If I'm at right place. I'm trying to update the password in IT glue this script. I'm getting this error.

Set-ITGluePasswords : Too many automatic redirections were attempted.
At C:\***\****\****\Ad password.ps1:142 char:1
+ Set-ITGluePasswords -organization_id $org_id -id $password_id -data $ ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Set-ITGluePasswords

Following is code. 

function Set-ITGluePasswords {
    [CmdletBinding(DefaultParameterSetName = 'update')]
    Param (
        [CmdletBinding(DefaultParameterSetName = 'update')]
        [Nullable[Int64]]$organization_id = $null,

        [CmdletBinding(DefaultParameterSetName = 'update')]
        [Nullable[Int64]]$id = $null,

        [CmdletBinding(DefaultParameterSetName = 'update')]
        [Boolean]$show_password = $false, # Passwords API defaults to $false

        [CmdletBinding(DefaultParameterSetName = 'update')]
        [CmdletBinding(DefaultParameterSetName = 'bulk_update')]
        [Parameter(Mandatory = $true)]
        $data
    )

    $resource_uri = ('/passwords/{0}' -f $id)

    if ($organization_id) {
        $resource_uri = ('/{0}/passwords/{1}' -f $organization_id, $id)
    }

    if ($show_password) {
        $resource_uri = $resource_uri + ('?show_password=true') # using $True in PS results in 'True' (uppercase T), so explicitly writing out 'true' is needed
    }

    $body = @{}

    $body += @{'data' = $data}

    $body = ConvertTo-Json -InputObject $body -Depth 2

    try {
        $ITGlue_Headers.Add('x-api-key', (New-Object -TypeName System.Management.Automation.PSCredential -ArgumentList 'N/A', $ITGlue_API_Key).GetNetworkCredential().Password)
        $rest_output = Invoke-RestMethod -method 'PATCH' -uri ($baseURI+ $resource_uri) -headers $ITGlue_Headers `
            -body $body -ErrorAction Stop -ErrorVariable $web_error
    } catch {
        Write-Error $_
    } finally {
        $ITGlue_Headers.Remove('x-api-key') >$null # Quietly clean up scope so the API key doesn't persist
    }

    $data = @{}
    $data = $rest_output 
    return $data
}

Function GET-Temppassword([int]$length, [string[]]$sourcedata) {
For ($loop=1; $loop –le $length; $loop++) {

            $TempPassword+=($sourcedata | GET-RANDOM)
            }
return $TempPassword
}

$key = "********"
#import-module ITGLUEAPI

$baseURI = "*******"
$headers = @{
    "x-api-key" = $key
}
   
   $org_id="*****"
   $data = @{
    'type' = 'passwords'
    'attributes' = @{
        
        'name' = '***'
        'username' = '***'
        'password' = $Pass
        'notes' = "Admin credentials for the domain admin account"
        'password-category-id' = '****'
        'password-category-name' = 'Active Directory'
        'organization_id' = $org_id

    }
}
$password_id ="*****"
Set-ITGluePasswords -organization_id $org_id -id $password_id -data $data

**Comment by ecspresso** [comment]
@ggill27 Could you post your code again but with better formatting? Perhaps wrap all of your code in a code block, it is difficult to help you with the current formatting.

**Comment by ggill27** [comment]
`function Set-ITGluePasswords {
[CmdletBinding(DefaultParameterSetName = 'update')]
Param (
[CmdletBinding(DefaultParameterSetName = 'update')]
[Nullable[Int64]]$organization_id = $null,

    [CmdletBinding(DefaultParameterSetName = 'update')]
    [Nullable[Int64]]$id = $null,

    [CmdletBinding(DefaultParameterSetName = 'update')]
    [Boolean]$show_password = $false, # Passwords API defaults to $false

    [CmdletBinding(DefaultParameterSetName = 'update')]
    [CmdletBinding(DefaultParameterSetName = 'bulk_update')]
    [Parameter(Mandatory = $true)]
    $data
)

$resource_uri = ('/passwords/{0}' -f $id)

if ($organization_id) {
    $resource_uri = ('/{0}/passwords/{1}' -f $organization_id, $id)
}

if ($show_password) {
    $resource_uri = $resource_uri + ('?show_password=true') # using $True in PS results in 'True' 
    (uppercase T), so explicitly writing out 'true' is needed
}

$body = @{}

$body += @{'data' = $data}

$body = ConvertTo-Json -InputObject $body -Depth 2

try {
      $ITGlue_Headers.Add('x-api-key', (New-Object -TypeName 
       System.Management.Automation.PSCredential -ArgumentList 'N/A', 
       $ITGlue_API_Key).GetNetworkCredential().Password)
       $rest_output = Invoke-RestMethod -method 'PATCH' -uri ($baseURI+ $resource_uri) -headers 
       $ITGlue_Headers -body $body -ErrorAction Stop -ErrorVariable $web_error
   }
   catch {
        Write-Error $_
   }
    finally {
        $ITGlue_Headers.Remove('x-api-key') >$null # Quietly clean up scope so the API key doesn't persist
    }

     $data = @{}
     $data = $rest_output 
      return $data
}

Function GET-Temppassword([int]$length, [string[]]$sourcedata) {
For ($loop=1; $loop –le $length; $loop++) {

        $TempPassword+=($sourcedata | GET-RANDOM)
        }
return $TempPassword
}

$key = "********"
#import-module ITGLUEAPI

$baseURI = "*******"
$headers = @{
  "x-api-key" = $key
}

$org_id="*****"
$data = @{
'type' = 'passwords'
'attributes' = @{

    'name' = '***'
    'username' = '***'
    'password' = $Pass
    'notes' = "Admin credentials for the domain admin account"
    'password-category-id' = '****'
    'password-category-name' = 'Active Directory'
    'organization_id' = $org_id

}
}
`

**Comment by ggill27** [comment]
can anyone help me to resolve this error ?

`Set-ITGluePasswords : Too many automatic redirections were attempted.
At C:*******\Ad password.ps1:142 char:1

Set-ITGluePasswords -organization_id $org_id -id $password_id -data $ ...
  + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
  + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Set-ITGluePasswords`

**Comment by ecspresso** [comment]
The function `Set-ITGluePasswords` in the file `passwords.ps1` contains some bugs addressed in #47. Either wait for it to get pushed to the main branch or download and update your local code. Try set a password after that and see if the error persists.

**Comment by adrianwells** [comment]
@ggill27 this should be fixed now with @ecspresso's PR #47 being merged into v2.0.4. Closing this issue, if there is still an issue please re-open this issue. Thank you.

**Comment by ggill27** [comment]
This issue still exists

**Comment by adrianwells** [comment]
Re-opening as @ggill27 reports this issue still exists and closing #57 as it's the same reported issue.

**Comment by adrianwells** [comment]
@ggill27 - When I test`Set-ITGluePasswords`, it successfully updates existing password data using ITGlueAPI module v2.0.4 and v2.0.5.  Please report which version of the ITGlueAPI module is being used? This cmdlet can help you get that information, `Get-Module -Name ITGlueAPI`

**Comment by ecspresso** [comment]
You can remove this part: `$body = ConvertTo-Json -InputObject $body -Depth 10`, the wrapper will convert to JSON for you.

Change this part: `Add-ITGlueBaseURI -base_uri 'https://.itglue.com/"organisationID"'` to `Add-ITGlueBaseURI -data_center EU` or `Add-ITGlueBaseURI -data_center US`. Base URI is meant to set the data center where you have your data stored (in EU or US). In your data is in EU, your URL will be _api.eu.itglue.com_ and if it is in the US, it will be _api.itglue.com_.

All the functions will handle the parameters like organisation id. I.e. if you want to change the password in IT Glue via the relationship route (`PATCH /organizations/:org_id/relationships/passwords/:id`), you need to supply `org_id` and `id` via the parameters `-organization_id` and `-id` (in addition to `-body`). The function will format the url as needed.

**Comment by adrianwells** [comment]
@ggill27 - to add @ecspresso's comments, here is example code that successful demonstrates creating an embedded password to an IT Glue Configuration, gets the ID of that password, then updates the password information. Of course, values like `organization_id` and `resource_id` will need to be adjusted for your scenario:

```
# Load the module
Import-Module ITGlueAPI.psd1

# Confirm the version being used
Get-Module ITGlueAPI

# Add the IT Glue API key
Add-ITGlueAPIKey -Api_Key "Your IT Glue API Key"

# Create a new embedded password for an existing configuration item 
$body = @{
	type = 'passwords'
	attributes = @{	   
		organization_id = 2425151
		name = 'Test password API for Jan 23 2019'
		username = 'root'
		password = 'testpasswordexample'
		resource_id = 10844996
		resource_type = 'Configuration'
	} 
}
$result = New-ITGluePasswords -data $body

# View results
$result.data | Format-List

# Get the password that was created
$CreatedPassword = Get-ITGluePasswords -filter_name 'Test password API for Jan 23 2019'

# Update the password created in the prior step
$body = @{
	type = 'passwords'
	attributes = @{	   
		organization_id = 2425151
		id = $CreatedPassword.data.id
		name = 'Test password API for Jan 23 2019 CHANGED'
		username = 'root'
		password = 'testpasswordexampleDidItChange'
	} 
}
$result = Set-ITGluePasswords -data $body

# View results
$result.data | Format-List
```

Please let us know if you are all set with this now?

**Comment by ggill27** [comment]
`
$CreatedPassword = Get-ITGluePasswords -filter_name 'test' 
$body = @{
	type = 'passwords'
	attributes = @{	   
		organization_id = $CreatedPassword.data[0].attributes.'organization-id'
		id = $CreatedPassword.data.id
		name = $CreatedPassword.data[0].attributes.name
		username = $CreatedPassword.data[0].attributes.username
		password = 'testpasswordexampleDidItChange'
	} 
}`

$createPassword gets all the details of the test user.
When I run the command '$result = Set-ITGluePasswords -data $body '
 I'm getting following error

`Set-ITGluePasswords : {"errors":[{"status":401,"title":"Unauthorized","detail":"Unauthorized resource 
access","source":{"pointer":"id"}}]}
At line:1 char:11
+ $result = Set-ITGluePasswords -data $body
+           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Set-ITGluePasswords`

**Comment by ggill27** [comment]
It works, There was an issue with API key
