### ISSUE TITLE
Remove-ITGlueContacts contains wrong paths

### ISSUE THREAD

**Issue by ecspresso** [itglue/powershellwrapper#63]
Function `Remove-ITGlueContacts` contains the paths:
`$resource_uri = ('/configurations/{0}' -f $id)` 
`$resource_uri = ('/organizations/{0}/relationships/configurations/{1}' -f $organization_id, $id)`.

`configurations` needs to be replaced with `contacts` (since we are working with contacts and not configurations).

**Comment by adrianwells** [comment]
Thanks @ecspresso! Closing this issue as the PR has been merged a new release v2.0.6 has been created.
