### ISSUE TITLE
Remove-ITGlueConfigurations fail if $id variable is defined

### ISSUE THREAD

**Issue by DarrenWhite99** [itglue/powershellwrapper#65]
**Steps to reproduce**
Set $id to a number, then call Remove-ITGlueConfigurations with a valid Data value.

PS C:\> $id=123456
PS C:\> Remove-ITGlueConfigurations -Data $ValidDataBody

**Expected behavior**

Configuration IDs specified in $ValidDataBody should be deleted.

**Actual behavior**

PS C:\> Remove-ITGlueConfigurations -Data $ValidDataBody
VERBOSE: DELETE https://api.itglue.com/configurations/123456 with -1-byte payload
Remove-ITGlueConfigurations : The remote server returned an error: (404) Not Found.

**Additional Details**
The function works when $id is not defined. This can be confirmed by running:
PS C:\> Clear-Variable id; Remove-ITGlueConfigurations -Data $ValidDataBody

It appears that the function was created by cloning another function, which used the $id parameter. The $resource_uri variable is updated to include the $id value even though $id is not a defined parameter and is not initialized in the function.

**Comment by adrianwells** [comment]
@DarrenWhite99 thanks for reporting, @ecspresso's recent PR works to address this issue which is now part of [version v2.0.7](https://github.com/itglue/powershellwrapper/releases/tag/v2.0.7). Please confirm and close out the issue if all is looking well now. Thank you.

**Comment by DarrenWhite99** [comment]
I have confirmed that with the change, the $id variable value no longer causes the function to fail.
Thanks!
