### ISSUE TITLE
Get-ITGlueOrganizations ignoring filters

### ISSUE THREAD

**Issue by jonwbstr** [itglue/powershellwrapper#69]
**Steps to reproduce**

$result = Get-ITGlueOrganizations -filter_organization_status_id 12345 -page_size 500 -filter_updated_at "2018-1-1,2018-2-1"

\#shows the page size and filter updated at in the link, but not the organization status id
$result.links
\# shows no filters set. this may be expected.
$result.meta

**Expected behavior**

Expecting only 5 results

**Actual behavior**

Getting 1000+  results.
I thought the filters were part of the URI, and it appears the filters are being added to the body. However, some filters added to the body appear to be making their way to the URI just fine while others are not. Curious.

**Environment**

Please share additional details about your environment. Version information for:
* PowerShell:  5.1.14393.2636
* ITGlueAPI: 2.0.5
* Operating System: Windows 2016

**Comment by bjowol** [comment]
I'm having the same problem. This creates another problem for us as we have over 1000 organizations. This means that we have an issue regarding actually getting all the organizations! Id like to not hack my way around this.

we want to add our organization id's to our PSA system so that we can do itglue filtering based on or PSA data (master information) and not make IT-glue a part of our infrastructure.

**Comment by ecspresso** [comment]
How many organizations do you have and how many do you expect to get from the result? More that 500? I did some testing and `links` was always present, `null` if I got all results the first time. 

_Empty because I got all results in one call_
```posh
PS > Get-ITGlueOrganizations -filter_organization_status_id $_OrganizationId -filter_updated_at "2018-1-1,2018-2-1" | gm


   TypeName: System.Management.Automation.PSCustomObject

Name        MemberType   Definition
----        ----------   ----------
Equals      Method       bool Equals(System.Object obj)
GetHashCode Method       int GetHashCode()
GetType     Method       type GetType()
ToString    Method       string ToString()
data        NoteProperty Object[] data=System.Object[]
links       NoteProperty System.Management.Automation.PSCustomObject links=
meta        NoteProperty System.Management.Automation.PSCustomObject meta=@{current-page=1; next-page=; prev-page=; total-pages=1; total-count=6; filters=}
```

_Present becaure I there are more then 2 results_
```posh
PS > Get-ITGlueOrganizations -filter_organization_status_id $_OrganizationId -page_size 2 -filter_updated_at "2018-1-1,2018-2-1" | gm


   TypeName: System.Management.Automation.PSCustomObject

Name        MemberType   Definition
----        ----------   ----------
Equals      Method       bool Equals(System.Object obj)
GetHashCode Method       int GetHashCode()
GetType     Method       type GetType()
ToString    Method       string ToString()
data        NoteProperty Object[] data=System.Object[]
links       NoteProperty System.Management.Automation.PSCustomObject links=@{self=https://api.eu.itglue.com/organizations?filter%5Bupdated_at%5D=2018-1-1%2C2018-2-1&page%5Bnumber%5D=1&page%5Bsize%5D=2; nex...
meta        NoteProperty System.Management.Automation.PSCustomObject meta=@{current-page=1; next-page=2; prev-page=; total-pages=3; total-count=6; filters=}


PS GitHub:\>
```

**Comment by bjowol** [comment]
> 
> 
> How many organizations do you have and how many do you expect to get from the result? More that 500? I did some testing and `links` was always present, `null` if I got all results the first time.
> 
> _Empty because I got all results in one call_
> 
> ```powershell
> PS > Get-ITGlueOrganizations -filter_organization_status_id $_OrganizationId -filter_updated_at "2018-1-1,2018-2-1" | gm
> 
> 
>    TypeName: System.Management.Automation.PSCustomObject
> 
> Name        MemberType   Definition
> ----        ----------   ----------
> Equals      Method       bool Equals(System.Object obj)
> GetHashCode Method       int GetHashCode()
> GetType     Method       type GetType()
> ToString    Method       string ToString()
> data        NoteProperty Object[] data=System.Object[]
> links       NoteProperty System.Management.Automation.PSCustomObject links=
> meta        NoteProperty System.Management.Automation.PSCustomObject meta=@{current-page=1; next-page=; prev-page=; total-pages=1; total-count=6; filters=}
> ```
> 
> _Present becaure I there are more then 2 results_
> 
> ```powershell
> PS > Get-ITGlueOrganizations -filter_organization_status_id $_OrganizationId -page_size 2 -filter_updated_at "2018-1-1,2018-2-1" | gm
> 
> 
>    TypeName: System.Management.Automation.PSCustomObject
> 
> Name        MemberType   Definition
> ----        ----------   ----------
> Equals      Method       bool Equals(System.Object obj)
> GetHashCode Method       int GetHashCode()
> GetType     Method       type GetType()
> ToString    Method       string ToString()
> data        NoteProperty Object[] data=System.Object[]
> links       NoteProperty System.Management.Automation.PSCustomObject links=@{self=https://api.eu.itglue.com/organizations?filter%5Bupdated_at%5D=2018-1-1%2C2018-2-1&page%5Bnumber%5D=1&page%5Bsize%5D=2; nex...
> meta        NoteProperty System.Management.Automation.PSCustomObject meta=@{current-page=1; next-page=2; prev-page=; total-pages=3; total-count=6; filters=}
> 
> 
> PS GitHub:\>
> ```

ill test and check again.
The point is that i want a list of all of our organizations, statuses, id's and names. this is data coming from our PSA, but not the ID. This list will be over 1500 customers and has to be compleate and no duplicates.

**Comment by ecspresso** [comment]
You can try looping on links.next, a simple way to do it would be like this
```posh
$data = @()
$pagenr = 1
do {
    $apicall = Get-ITGlueOrganizations -page_number ($pagenr++)
    $data += $apicall.data
} while($apicall.links.next)
```

**Comment by adrianwells** [comment]
Thank you @ecspresso. @bjowol closing this issue for now. If there are additional updates or information about this, then re-open the issue.
