### ISSUE TITLE
Upload multiple attachments

### ISSUE THREAD

**Issue by wpouseele** [itglue/powershellwrapper#7]
Hi,

It is unclear to me how I can upload multiple attachments via the API.

Passing an array with multiple file traits when creating an asset does not work and I got the feedback from support that this is not possible. I should instead create an asset en run an update call for each additional attachment. However, this doesn't seem to work neither since updating the asset keeps only the last added attachment.

Thanks,
Wim

**Comment by boast1570** [comment]
I'm struggling with getting any attachment uploads to a configuration. What does your powershell look like? My Base64 conversion is done through $base64string = [Convert]::ToBase64String([IO.File]::ReadAllBytes($FileName))

$body = @{
    data = @{
        type = 'configurations'
        attributes = @{
            file = @{
            content = "$base64string"
            file_name = 'testfile'
            }
        }
    }
}
Set-ITGlueConfigurations -data $body -organization_id "fakeorg" -id "fakeid"

**Comment by wpouseele** [comment]
@boast1570 I don't think you can upload a file to ITGlueConfigurations ;-)
You should target a flexible asset with an upload item addded and then run the corresponding cmdlet (Set-ITGlueFlexibleAssets or New-ITGlueFlexibleAssets)

**Comment by boast1570** [comment]
Can't seem to get it into a Flexible asset via the an Upload field type either. Keep getting `Invoke-RestMethod : {"errors":[{"status":422,"title":"Unprocessable Entity","detail":"Request contains invalid trait 
keys","source":{"pointer":"data/attributes/traits"}}]}
At C:\Program Files\WindowsPowerShell\Modules\ITGlueAPI\Resources\FlexibleAssets.ps1:12 char:20
`
`$body = @{
    data = @{
        type = 'flexible_assets'
        attributes = @{
            organization_id = 2210954
            flexible_asset_type_id = 80121
            traits = @{   
                Device = 'Test'
                file = @{
                    content = "$base64string"
                    file_name = 'wo-mdf-stack-1.txt'
                }
            }
        }
    }
}

New-ITGlueFlexibleAssets -data $body`

**Comment by ecspresso** [comment]
@boast1570 Is the field named "file"? I created a field with the name "fil" and content type "upload", this code worked for me. It could of course be that `Device = 'Test'` also is the error, have you checked all spellings?

```
$body = @{
    data = @{
        type = 'flexible_assets'
        attributes = @{
            organization_id = 123
            flexible_asset_type_id = 456
            traits = @{
                fil = @{
                    content = "R0lGODlhABAQAIAAAAAAAP///yH7BAEAAAAALAAAAAAEAABAAAIBRAA5"
                    file_name = "test.png"
                }
            }
        }
    }
}

New-ITGlueFlexibleAssets -data $body
```

**Comment by boast1570** [comment]
I may have figured it out. I made the D in Device lowercase and it successfully added the record, with the file to the Flexible asset. Good stuff! Now I'm working on retaining line breaks in the base64 encoded file.  Sorry for hijacking your issue @wpouseele

**Comment by wpouseele** [comment]
Back to the original question: has anyone been able to upload multiple attachments?

Thanks.

**Comment by ecspresso** [comment]
I could not figure out any way to do this so I asked their support and it is not possible at the moment.

**Comment by ecspresso** [comment]
Someone summarized everything in this post and suggested changes. Please vote for it if you agree.
https://itglue.ideas.aha.io/ideas/ITGPM-I-2969

**Comment by adrianwells** [comment]
@CalebAlbers is it possible to tag this indicating it's awaiting IT Glue API updates?

**Comment by CalebAlbers** [comment]
Hey all,

IT Glue released a proper endpoint for managing attachments (https://api.itglue.com/developer#attachments). I've created #71 for tracking progress in adding this functionality to the module. I'm hoping to have the added functions done by Wednesday. I'll update this thread once the updated module code is pushed. It should make things a lot easier, as a bulk-update operation is included.

Cheers

**Comment by Oliver-NC** [comment]
Hi all, 

Please also help me with the following. 

I have a Flexible Asset Type and a field named Mailbox Forwards in there. I want to update the Flex Asset and using the code below:

$body = @{
    data = @{
        type = 'flexible_assets'
        attributes = @{
            organization_id = (id of course)
            flexible_asset_type_id = (flex type of id of course)
            traits = @{
                Mailbox_Forwards = @{
                    
                    default_value = "BOOM!"
                }
            }
        }
    }
}

New-ITGlueFlexibleAssets -data $body

**Comment by Oliver-NC** [comment]
This is the error message:

New-ITGlueFlexibleAssets : {"errors":[{"status":"unprocessable_entity","title":"Bad request","detail":"Invalid type: ''. Expected: 'flexible_assets'","source":{"pointer":["data","type"]}}]}
At line:1 char:1
+ New-ITGlueFlexibleAssets -data $body
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,New-ITGlueFlexibleAssets

**Comment by Oliver-NC** [comment]
Error: (Sorry for re-post) 

New-ITGlueFlexibleAssets : {"errors":[{"status":"unprocessable_entity","title":"Bad request","detail":"Invalid type: ''. Expected: 'flexible_assets'","source":{"pointer":["data","type"]}}]}
At line:1 char:1
+ New-ITGlueFlexibleAssets -data $body
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,New-ITGlueFlexibleAssets

**Comment by adrianwells** [comment]
@Oliver-NC, Hello. May you please consider creating a [new issue](https://github.com/itglue/powershellwrapper/issues/new/choose) as what you are reporting appears to be a different topic. Thank you.

**Comment by adrianwells** [comment]
Closing this issue as Oliver-NC created a separate issue for their request and there's new issue already created by Caleb for this enhancement.
