### ISSUE TITLE
Retrieving passords filtered by organization_id not returning passwords

### ISSUE THREAD

**Issue by bjowol** [itglue/powershellwrapper#70]
running this command:
`(Get-ITGluePasswords -id 973936509305037 -show_password $true).data.attributes`
returns this output. Nothing wrong here, works as intended.
![bilde](https://user-images.githubusercontent.com/14833255/52331231-e6f53000-29f7-11e9-9edb-d729b9c6f943.png)

however, the problem is where you request all the passwords from an organization. 
`(Get-ITGluePasswords -filter_organization_id 'xxxxxxxxxxxxxx' -show_password $true).data.attributes`

An error is returned
![bilde](https://user-images.githubusercontent.com/14833255/52333039-83213600-29fc-11e9-8f50-a7ca61aff94b.png)

So as of right now i cannot get all the password out via PS without doing a lot of api calls (3500).

**Comment by brianmccarty** [comment]
My reading of the API documentation [https://api.itglue.com/developer/](https://api.itglue.com/developer/)
**show_password** requires the **-id** to be passed to the request.

**Comment by ecspresso** [comment]
It looks like @brianmccarty is correct. Here is some code to try it yourself.
```posh
$ITGlue_Headers = @{
    'x-api-key' = [PSCredential]::New('null', $(Get-ITGlueAPIKey)).GetNetworkCredential().Password
    'Content-Type' = 'application/vnd.api+json'
}

# Does not show password
(Invoke-RestMethod -method 'GET' -uri 'http://api.eu.itglue.com/passwords?show_password=true' -headers $ITGlue_Headers -body @{'filter[id]' = 4918113}).data.attributes

# Shows password
(Invoke-RestMethod -method 'GET' -uri 'http://api.eu.itglue.com/passwords/4918113?show_password=true' -headers $ITGlue_Headers).data.attributes
```

**Comment by CalebAlbers** [comment]
Agreed. This is unfortunately something IT Glue's API doesn't support. Tagging as "awaiting API update" and closing this issue for now.

Feel free to share out an IT Glue Idea link if you submit one. I think it's a worthwhile addition.

**Comment by bjowol** [comment]
ITGPM-I-3662****
