### ISSUE TITLE
Support Attachments & Related Items

### ISSUE THREAD

**Issue by CalebAlbers** [itglue/powershellwrapper#71]
**Is your feature request related to a problem? Please describe.**
As of March 13, 2019, IT Glue has added support for the update, bulk update, and destroy operations on attachments for API endpoints. Support for these actions should be added in to the next revision of the PowerShell module.

**Describe the solution you'd like**
The API endpoint follows our standard convention, and should be implemented with the following functions:
 - `New-ITGlueAttachments`
 - `Set-ITGlueAttachments` (with support for bulk update)
 - `New-ITGlueRelatedItems`
 - `Set-ITGlueRelatedItems` (with support for bulk update)

**Additional context**
Release Notes:
 - https://kb.itglue.com/hc/en-us/articles/360025294931-Release-Notes-2019-03-13-API-

Documentation:
 - https://api.itglue.com/developer#attachments
 - https://api.itglue.com/developer#related-items

**Comment by s0nders** [comment]
> @CalebAlbers Do we have an ETA on this? I needed this functionality for a script so I just added it myself locally; however, I'd love to see this added to the official module, and if you're busy with other things, I'd be happy to put together a pull request to implement this functionality.

Could you provide the code you used to accomplish this? I'm trying to work on this myself but im not having any luck.

**Comment by ecspresso** [comment]
#87 and #88 should have the could you need.

**Comment by s0nders** [comment]
> #87 and #88 should have the could you need.

I wasn't able to get it work, tried making an asset for attachments and everything I attempted to upload failed. I don't know if I missing something (pretty new to the ITGlue API so I could be missing something pretty obvious )

**Comment by ecspresso** [comment]
> I wasn't able to get it work, tried making an asset for attachments and everything I attempted to upload failed. I don't know if I missing something (pretty new to the ITGlue API so I could be missing something pretty obvious )

Did you start a new session or reloaded the module after doing changes to the module?  
`Import-Module ITGlueAPI -Force`
&nbsp;
If yes, I can look at it later this week and see if I can give you a working example.

**Comment by CalebAlbers** [comment]
This is now supported via #87 and #88

New PS Gallery release is on the way
