### ISSUE TITLE
"Request contains invalid trait keys"

### ISSUE THREAD

**Issue by somecoulombs** [itglue/powershellwrapper#72]
**Steps to reproduce**
When passing a hashtable as a Data parameter to update Flexible assets (Specifically Active Directory), trait keys are valid yet an error is returned stating:

```
set-ITGlueFlexibleAssets : {"errors":[{"status":422,"title":"Unprocessable Entity","detail":"Request contains invalid trait
keys","source":{"pointer":"data/attributes/traits"}}]}
```

My example hashtable looks like this:
```

        $data =  @{
              Type = 'flexible-assets'
              Attributes = @{
                 'Organization-ID' = '789694'
                  Traits = @{
                      'fqdn-domain-full-name' = "test"
                      'ad-domain-pre-windows-2000-name-aka-short-name' = "test"
                   }
              }
          }
```

**Expected behavior**

Asset updates without error

**Actual behavior**

Receive error in screenshot below:
![image](https://user-images.githubusercontent.com/5713542/54776223-0500a380-4be6-11e9-9954-828292c80636.png)

**Environment**

Please share additional details about your environment. Version information for:
* PowerShell - 5.1
* ITGlueAPI - 2.0.5
* Operating System - Windows 10 Pro

My trait keys appear to be correct. I'm not sure if there's something I missed, or if the error is incorrect and I've forgotten something different.

Thanks in advance!

**Comment by Absoblogginlutely** [comment]
Is this because you don't have the flexible_asset_type_id value set?
When running the activedirectory.ps1 script I have the following output:-
$api__body | convertto-json
{
    "type":  "flexible_assets",
    "attributes":  {
                       "organization_id":  "1892324",
                       "flexible_asset_type_id":  "102735",
                       "traits":  {
                                      "schema-master":  "10122455",
                                      "ad-level":  "2016",
                                      "relative-id-rid-master":  "10122455",
                                      "infrastructure-master":  "10122455",
                                      "global-catalog-servers-domain-controllers":  "10122455",
                                      "domain-short-name":  "build",
                                      "domain-full-name":  "build.com",
                                      "pdc-emulator-master":  "10122455",
                                      "domain-naming-master":  "10122455",
                                      "forest-name":  "build"
                                  }
                   }
}


![Screenshot - 3_21_2019 , 5_35_31 PM](https://user-images.githubusercontent.com/21364480/54786709-f1facd00-4bff-11e9-8df0-31cf60b09bca.png)

**Comment by ecspresso** [comment]
Try changing the T in Traits to lower case.

This works:
```
$data = @{
    Type = "flexible-assets"
    Attributes = @{
        'Organization-ID' = 2504761
        traits = @{
            type = "Other"
            'domain-s' = 944532011729098
            'webmail-url' = "awdawdwa"
        }
    }
}

Set-ITGlueFlexibleAssets -id 944531707543784 -data $data
```
This does not work:
```
$data = @{
    Type = "flexible-assets"
    Attributes = @{
        'Organization-ID' = 2504761
        Traits = @{
            type = "Other"
            'domain-s' = 944532011729098
            'webmail-url' = "awdawdwa"
        }
    }
}

Set-ITGlueFlexibleAssets -id 944531707543784 -data $data
```

I know that my flexible asset does not match yours but it seems that all keys below and including `traits` has to be lower case. This does not seem to apply for other end points where traits is not present (i.e. conatcts, did not test on anything else).

**Comment by somecoulombs** [comment]
Thank you both very much for helping!  @ecspresso was correct, having the capital 'T' in Traits was the culprit.  I changed it to lowercase and the asset updated without error. 

Thank you, thank you!
