### ISSUE TITLE
Powershell Output

### ISSUE THREAD

**Issue by Oliver-NC** [itglue/powershellwrapper#74]
Hi all,

I am using the power-shell wrapper to create documentation in IT Glue from Office 365. The data that comes across is quite messy. Anyone have ideas on how to create some neat tables and lists?

**Comment by Oliver-NC** [comment]
Sorry to shed more information, 
The data pulled from Office 365 via Powershell in a single line. I would like to add a line break or have them in point/bullet/numbered form. How is this done into a IT Glue flex asset and text box?

**Comment by ecspresso** [comment]
You can format your data as a HTML table:
```
$exampleHTMLTabel= '<div>
    <table>
        <tbody>
            <tr>
                <td>Name</td>
                <td>Version</td>
                <td>Default</td>
            </tr>
            <tr>
                <td>Example 1</td>
                <td>1.1</td>
                <td>True</td>
            </tr>
            <tr>
                <td>Example 2</td>
                <td>1.2</td>
                <td>False</td>
            </tr>
            <tr>
                <td>Example 3</td>
                <td>1.3</td>
                <td>False</td>
            </tr>
        </tbody>
    </table>
</div>'

$data = @{
    type = 'flexible-assets'
    attributes = @{
        id = $flexible_asset_id
        traits = @{
            'exampleHTMLTabel' = $exampleHTMLTabel
        }
    }
}
Set-ITGlueFlexibleAssets -data $data
```

I used this when formating data from an Hyper-V host an I had an unkown number of rows. Here is an example with `Get-VMHostSupportedVersion`:
```
$supportedVersionsHTML = '<div>
    <table>
        <tbody>
            <tr>
                <td>Name</td>
                <td>Version</td>
                <td>Default</td>
            </tr>
            {0}
        </tbody>
    </table>
</div>' -f ((Get-VMHostSupportedVersion).foreach{
    '<tr>
        <td>{0}</td>
        <td>{1}</td>
        <td>{2}</td>
    </tr>' -f $_.Name, $_.Version, $_.IsDefault} | Out-String)


$data = @{
    type = 'flexible-assets'
    attributes = @{
        id = $flexible_asset_id
        traits = @{
            # Supported OS versions
            'vm-host-supported-versions' = $supportedVersionsHTML
        }
    }
}
Set-ITGlueFlexibleAssets -data $data
```

Do a `ForEach` to get all VMs (and in seperate lines) and `| Out-String` because it did not work otherwise (can remember what the problem was).

**Comment by ecspresso** [comment]
I could not get new lines to work with textbox.

**Comment by ecspresso** [comment]
Figured out new lines: ``"first line`nsecond line"``. This will convert to `"first line\nsecond line"` i JSON (where `\n` is JSON new line). You have to use `"` and not `'`, will not work otherwise.

**Comment by adrianwells** [comment]
Thank you @ecspresso. @Oliver-NC does this resolve your issue, if yes, may you please confirm and comment then close this issue?

**Comment by adrianwells** [comment]
Closing this issue due as this seems resolved and there's been no reply for some time.
