### ISSUE TITLE
Get-ITGlueOrganizations -filter_name - Customers with Commas

### ISSUE THREAD

**Issue by nsnoonan** [itglue/powershellwrapper#76]
**Steps to reproduce**

Attempt to use [Get-ITGlueOrganizations] and filter on a company name in IT Glue that contains one or more commas.
`Get-ITGlueOrganizations -filter_name "company with a comma, inc."`

**Expected behavior**

The return of an object containing data on the filtered company.

**Actual behavior**

The returned object contains no data.
```
data meta                                                                              links
---- ----                                                                              -----
{}   @{current-page=1; next-page=; prev-page=; total-pages=0; total-count=0; filters=}
```
**Environment**

* PowerShell - 5.0.10240.17443
* ITGlueAPI - 2.0.0
* Operating System - Windows 10 Enterprise x64

**Comment by ecspresso** [comment]
This does not seem to be a problem with the wrapper but rather with the API. You can filter on muliple names separated by comma. Say that you have you the organizations `Foo` and `Bar`. You could get both of then with one call using `Get-ITGlueOrganizations -filter_name 'Foo, Bar'`, the result would look like this: 

```
id      type          attributes
--      ----          ----------
1234567 organizations @{name=Foo; ...}
7654321 organizations @{name=Bar; ...}
```
This means that `"company with a comma, inc."` is being interpeted by the API as `company with a comma` and `inc.` instead.

**Comment by nsnoonan** [comment]
ok, I see.  Is there a way, then, to escape the commas?  I've tried several methods and have been unsuccessful so far.

**Comment by ecspresso** [comment]
No, not that I know of. The documentations does not say anything about wild cards and it seems it only works with exact matches. Try contacting support, they might know something.

**Comment by RMMSecurity** [comment]
How can we get this logged as a bug in the api? Or at least documented how to handle this. I have organizations with commas in them and this breaks that.

**Comment by ecspresso** [comment]
I think the only option is to contact their support.

**Comment by DarrenWhite99** [comment]
I just successfully tested using a backslash to escape the comma in the organization name.  Multiple organizations are still supported with the comma operator as well.
Example: `Get-ITGlueOrganizations -filter_name 'ABC Systems\, Inc.,Happy Frog Labs'`
_(Watch out for dropping a trailing period in the org name, an exact match is still needed)_

**Comment by nsnoonan** [comment]
I did open a ticket with ITG and they have responded that they resolved this issue.  It appears to be working from my testing.
