### ISSUE TITLE
Get-ITGlueOrganizations -filter_name wildcards

### ISSUE THREAD

**Issue by IanPennebaker** [itglue/powershellwrapper#77]
I am hoping to use this command to get all orgs that contain a certain word, for instance:
`Get-ITGlueOrganizations -filter_name "*xyz*"`

Is this possible? I did not see anything in regards to wildcards in the documentation.

**Comment by CalebAlbers** [comment]
Hey Ian!

Unfortunately, IT Glue's filtering is only based off of string matching or date ranges, and does not support wildcards. With that said, you could get all organizations and then filter the name in PowerShell using the `Where-Object` cmdlet:

```powershell
(Get-ITGlueOrganizations).data | Where-Object {$_.attributes.name -like "*xyz*"}  
```

Here's an example:
<img width="1200" alt="image" src="https://user-images.githubusercontent.com/7110138/60240767-a2fbae00-9866-11e9-9133-3e83823283b0.png">

**Comment by IanPennebaker** [comment]
Hi sorry to be a hassle, I'm completely stuck. So I'm running this command,
 `((Get-ITGlueOrganizations).data | Where-Object {$_.attributes.name -like "*cae*"}).attributes.name`
And it is retrieving the Org that contains cae, however when I run
`((Get-ITGlueOrganizations).data | Where-Object {$_.attributes.name -like "*wnc*"}).attributes.name`
it does not pull the org that contains WNC. This is the case for every org in our system, wnc is only one that does not work. Any ideas as to why this is happening? I checked the Name and Short Name in IT Glue. It is not due to capitals or spacing.

**Comment by Absoblogginlutely** [comment]
Does it show up when you just look at the get-itglueorganizations.data and not filter? Could it be that it's the 51st record and the system is returning results in 50 record pages? (or whatever the magic number is?)
I use the following code to make sure that connection is successful and retrieve the organization number(s)
`		$orglist=Get-ITGlueOrganizations -page_size 200
		
		If ($orglist) {
		$orgdata=$orglist.data
		#insert company name in the next line
		$org=$orgdata | ? {$_.attributes.name -like '*wnc*'}
		$orgnumber = $org.id
		}
If (!$orgnumber) {write-host "Organization can not be found - go to the organization in ITGlue and grab the id from the URL"} Else {Write-host "Organization number is $orgnumber"}
`

**Comment by IanPennebaker** [comment]
Page Size!!! 
Thanks for the tip that did it!

**Comment by ecspresso** [comment]
>  Could it be that it's the 51st record and the system is returning results in 50 record pages? (or whatever the magic number is?)

The magic number (max page size) would be 1000: https://kb.itglue.com/hc/en-us/articles/115001445108

If you want to grab everything and look through it later, here is a way (based on @brianmccarty's pull request.)

```posh
$data = @()
$page_number = 1
do{
    $api_call = Get-ITGlueConfigurations -page_size 1000 -page_number ($page_number++)
    foreach($_ in $api_call.data) {
        $data += $_
    }
} while($api_call.links.next)
```
You could also use a hash table
```posh
$data = @{}
$page_number = 1
do{
    $api_call = Get-ITGlueConfigurations -page_size 1000 -page_number ($page_number++)
    foreach($_ in $api_call.data) {
        $data["$($_.attributes.'organization-name')"] = $_
    }
} while($api_call.links.next)

# fastest way to access company named "foo" (does not work with wildcards)
> $data["foo"] 

id      type           attributes
--      ----           ----------
1234567 organizations @{organization-id=9745624; organization-name=foo...}
```
