### ISSUE TITLE
Update PowerShell Gallery to 2.0.7

### ISSUE THREAD

**Issue by ecspresso** [itglue/powershellwrapper#78]
PowerShell Gallery only has version 2.0.5 and the latest version 2.0.7. Can we push the latest version to PowerShell Gallery?

**Comment by adrianwells** [comment]
Thank you for pointing this out @ecspresso. @CalebAlbers may you please assist with this?

**Comment by adrianwells** [comment]
@CalebAlbers Hi. Now have v2.0.8 available, are you able to please help update the module?

**Comment by Entech-Ramon** [comment]
Anyway to get it updated to the latest? Still 2.0.5

**Comment by ecspresso** [comment]
@Entech-Ramon If you want to install the latest version manually, you can do this by downloading the latest files here and replace the files in `%userprofile%\Documents\WindowsPowerShell\Modules\ITGlueAPI`.

If that folder does not exist, you might have installed the module somewhere else: https://docs.microsoft.com/en-us/powershell/scripting/developer/module/installing-a-powershell-module?view=powershell-5.1

- `$PSHome\Modules` (%Windir%\System32\WindowsPowerShell\v1.0\Modules)
- `$Home\Documents\WindowsPowerShell\Modules` (%UserProfile%\Documents\WindowsPowerShell\Modules)
- `$Env:ProgramFiles\WindowsPowerShell\Modules` (%ProgramFiles%\WindowsPowerShell\Modules)

**Comment by adrianwells** [comment]
@ecspresso have been exploring using Azure Pipelines to automate publishing of this to PowerShell Gallery. It appears to be working though further tweaking is needed.
