### ISSUE TITLE
Expiration endpoint in the IT Glue API page

### ISSUE THREAD

**Issue by adrianwells** [itglue/powershellwrapper#79]
**Is your feature request related to a problem? Please describe.**
Add Expiration endpoint dates for assets

**Describe the solution you'd like**
Extend this module to take advantage of new API for Expiration endpoint dates for assets

**Additional context**
Per IT Glue announcement:

> Added the Expiration endpoint in the [IT Glue API page](https://api.itglue.com/developer). This resource allows you to view collected information about the expiration dates for your assets.

**Comment by CalebAlbers** [comment]
This is now supported via #82 

New PS Gallery release is on the way
