### ISSUE TITLE
Domains missing - Get-ITGlueDomains

### ISSUE THREAD

**Issue by kai-osthoff** [itglue/powershellwrapper#80]
Hi!
 Just stumbled over missing "Get-ITGlueDomains" cmdlet. Is there any reason missing that?

Is there any reason missing that out?
https://api.itglue.com/developer/#domains-index

**Comment by s0nders** [comment]
How come this hasn't been added to master in over a year?

**Comment by ecspresso** [comment]
> How come this hasn't been added to master in over a year?

This and other PRs need to be merged, I hope IT Glue gets to it soon.

**Comment by CalebAlbers** [comment]
I just merged the PR. New version is going to be published to PSGallery soon with this and other changes.
