### ISSUE TITLE
Get-ITGluePasswords is not showing the password

### ISSUE THREAD

**Issue by simonTIG** [itglue/powershellwrapper#84]
**Steps to reproduce**

When I run the following commands, the password attribute is missing from the output:
$pwds = Get-ITGluePasswords -show_password $True
$pwds = Get-ITGluePasswords -show_password $true
$pwds = Get-ITGluePasswords -show_password 1
$pwds = Get-ITGluePasswords

**Actual behavior**

I get the following output:

PS C:\Users\scateau> $pwds.data[0].attributes

organization-id           : 9954XXXXXX404662
organization-name         : XXXXXXXX
resource-url              : https://XXXXX.eu.itglue.com/99547XXXXX3404662/passwords/102239XXXXX32798
restricted                : False
my-glue                   : False
name                      : Pre-Shared Key
autofill-selectors        :
username                  :
url                       :
notes                     :
password-updated-at       : 2019-03-12T14:48:21.054Z
updated-by                :
updated-by-type           : User
resource-id               : 1022XXXXXX21497
cached-resource-type-name : Wireless
cached-resource-name      : test
password-category-id      :
password-category-name    :
created-at                : 2019-03-12T14:48:21.054Z
updated-at                : 2019-03-12T14:50:27.842Z
resource-type             : flexible-asset-traits
parent-url                : https://XXXXX.eu.itglue.com/99547XXX73404662/assets/995572XX514981-wireless/records/10223XX2489267

**Environment**

Version information for:
* PowerShell: 5
* ITGlueAPI
* Operating System : Windows 10 Pro 1809

**Comment by ecspresso** [comment]
Have you made sure the API key you are using has access to the passwords?

**Comment by simonTIG** [comment]
Yes I have made sure the API key has access to the passwords.

**Comment by ecspresso** [comment]
You need to specify the ID of the password when doing the API call. There are two paths in the API, index and show. Index will give you all passwords but now show the password. Show will give you one password and show the password in clear text (if you have set the permissions).

https://api.itglue.com/developer#passwords-index
https://api.itglue.com/developer#passwords-show

**Comment by simonTIG** [comment]
Thank you very much, querying for a specific password solved the issue for
me:
$password1 = get-itgluepasswords -id 10617319133555553

$password1.data.attributes


organization-id           : 995XXXXXX31781
organization-name         : XXXXXXXX)
resource-url              :
https://XXX.eu.itglue.com/9954XXX1781/passwords/1061XXX1403
restricted                : False
my-glue                   : False
name                      : Office account
autofill-selectors        :
username                  : XXXXXXXXX
url                       :
notes                     :
password-updated-at       : 2019-04-09T09:42:53.223Z
updated-by                : 1055887XXXX02
updated-by-type           : User
resource-id               : 106173XXXX67125
cached-resource-type-name : Licensing
cached-resource-name      : Microsoft Office 2013/2016 wkst-2015-01 2013 or
2016
password-category-id      :
password-category-name    :
created-at                : 2019-04-09T09:42:53.223Z
updated-at                : 2019-04-09T09:42:53.223Z
resource-type             : flexible-assets
parent-url                :
https://XXX.eu.itglue.com/99547XXX631781/assets/99557XXX9238-licensing/records/10617XXXX367125
password                  : XXXXX



Cheers




*Simon Cateau*Chief Technology Officer

T: +41 22 552 0111 <http://www.theitguys.ch> | E: simon@theitguys.ch  | W:
www.theitguys.ch

CONNECT WITH US    [image: LinkedIn]
<http://www.linkedin.com/company/the-it-guys-sarl>     [image: Google Plus]
<https://plus.google.com/+TheitguysCh>     [image: Twitter]
<https://www.twitter.com/theitguys>

*SECUREADVANTAGE  | THE LEADING ALL-IN-ONE IT MANAGEMENT SOLUTION FOR SMBs*

*24/7 MONITORING + UNLIMITED SUPPORT + GUARANTEED RESPONSE TIMES + SLA
BACKED + LOW MONTHLY FEE*
