### ISSUE TITLE
Remove-ITGlueConfigurations does not behave like Remove-ITGlueFlexibleAssets

### ISSUE THREAD

**Issue by somecoulombs** [itglue/powershellwrapper#93]
With Remove-ITGlueFlexibleAssets, it accepts an 'id' parameter where you can pass an asset ID to be deleted

Remove-ITGlueConfigurations does not accept an 'id' parameter, so it is not possible to specify one single configuration to be deleted.

**Comment by ecspresso** [comment]
This is should be because there is no endpoint in the API for removing a single configuration, only bulk destroy. 

The module could be built to handle this though since the type and structure are always the same, the module could handle the data structure here.

**Comment by CalebAlbers** [comment]
@ecspresso added support via PR #94 which was recently merged and is being released with v2.1.0
