### ISSUE TITLE
New-ITGlueFlexibleAssets - 'can't be blank' error

### ISSUE THREAD

**Issue by somecoulombs** [itglue/powershellwrapper#96]
**Steps to reproduce**
Create hash object, assign to $data variable

New-ITGlueFlexibleAssets -data $data

Describe the steps to reproduce the issue.
$itgluecompanyid is an integer
$notes is a string

```

        $data = @{
            Type = 'flexible-assets'
            Attributes = @{
                'Flexible_asset_type_id' = 67825
                'organization-id'        = $itgluecompanyID
                traits = @{
                    'friendly-name' = "iDRAC config $hostname"
                    'notes' = "$notes"
                }
            }
        }
        
New-ITGlueflexibleassets -data $data
```
**Expected behavior**

A new ITGlue flexible asset is created

I noticed this issue while building a new script, and I checked in on a few older scripts that use this command, and they're all having the same problem.

**Actual behavior**

New ITGlue flexible asset is not created, receive this message instead:

New-ITGlueflexibleassets : {"errors":[{"source":{"pointer":"/data/attributes/flexible-asset-traits.url"},"detail":["can't be blank"],"title":"Unprocessable Entity","status":422}]}
At line:1 char:9
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,New-ITGlueFlexibleAssets

**Screenshots**

I split the $notes variable and am showing only the first 9 lines to keep this screenshot at a manageable length

![image](https://user-images.githubusercontent.com/5713542/71921428-de046580-3156-11ea-8117-09aff34f8aba.png)

![image](https://user-images.githubusercontent.com/5713542/71921497-fd02f780-3156-11ea-8ef3-af9317d73510.png)

**Environment**

* PowerShell 5.1
* ITGlueAPI 2.0.5
* Operating System W10 Pro

**Comment by ecspresso** [comment]
Does your flexible asset contain a field named "url" and is it set to required?

**Comment by somecoulombs** [comment]
Oh man, I feel silly, I completely missed the '.url' at the end of that pointer.  Yep, that was it, looks like one of my colleagues might have reconfigured that flexible asset.

You're exceptional as always, thanks Emile!
